kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  type: LoadBalancer
  loadBalancerIP: 104.211.215.147
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
