apiVersion: v1
kind: Pod
metadata:
  name: avro-client
  namespace: kafka
spec:
  containers:
  - name: avro-client
    image: confluentinc/cp-schema-registry:5.2.1
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
